djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tweetapp.urls')),
    path("",include('django.contrib.auth.urls')),#kullanıcının kaydolabilmesi için falan.bunu yapınca login fln olusturuluyo ama htmlleri tabiiki kendimiz yapmamız lazım ve html için ana templatenin altına yeni bi registration isminde klasor acmamız lazım bunun içinede login logout htmlleri fln accaz zaten
]

djangotweet/tweetapp/urls.py
from django.urls import path
from . import views
app_name='tweetapp' #bunu kullanarak html içinde jinja ve reverse kullanabiliyoruz

urlpatterns = [
    path('',views.listtweet,name='listtweet'),
    path('addtweet/',views.addtweet,name='addtweet'),
    path('addtweetbyform/',views.addtweetbyform,name='addtweetbyform'),
    path('addtweetbymodelform/',views.addtweetbymodelform,name='addtweetbymodelform'),
    path('signup/',views.SignUpView.as_view(),name="signup"),#bu oncekiler gibi fonksiyon degil sınıf bu yuzden sonuna .as_view() diyerek bunu gorunuume cevirebiliyoruz
    path('deletetweet/<int:id>',views.DeleteTweet,name='DeleteTweet'),#id alabilmek içinde gordgn gibi yaptk şimdi listweet de delete kısmına link vercez
]

djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User #kullanıcının ismini fln alabilmek için

# Create your models here.
class Tweet(models.Model):
    #nickname=models.CharField(max_length=50) artık kullanıcılar giriş yaparak tweet attıgı için buna ihtiuyacım yok 258.video
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True)#burda user modelinden farklı odelle ilişki kurabilmek için foregn key kullandık User ı kullanıcagımızı soyledik bi gun bu kullanıcıyı sşilersem tweetlerininde silinmesi için ondeletecascate verdik ve null verdik ve migrationları yapcaz
    message=models.CharField(max_length=100)

    def __str__(self):
        #return f"Tweet nick : {self.nickname},Tweet message:{self.message}"
        return f"Tweet user : {self.username},Tweet message:{self.message}"

djangotweet/tweetapp/forms.py
#şuan aslında kullanıcıdan girdigi bilgileri alp kaydedip gene gosterebiliyoruz gene bunu yapıcaz ama buda farklı bi yolu djangonun kendi bi ozelligi
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet
#modelse cok benzer modelsde gosterdgmz gibi charfield gibi seyler vardır daha detaylı neler var gormek için django form fields ı arastırabilirsin
#biraz once html i kendm yazdm burda yazmayacaz bile kendi yazacak html i
class AddTweetForm(forms.Form):
    nickname_input=forms.CharField(label="Nickname",max_length=50)
    message_input=forms.CharField(label="Message",max_length=100,widget=forms.Textarea(attrs={"class":"tweetmessage"}))#widgetda yazacagımız alanınn buuyuuzesi için ve gene bu textareanın ozelliigi textareadad sınıf belirtince css le ustunde oynayabiliriz
#viewste bunu gorebilmek için bi fonksiyon olusturcaz ismi addtweetbyformolsun
'''
if request.method=="POST":
        print(request.POST)
    bize bu veri geldiginde hazır bir form dosyası gibi gelecek
    else:
        return render('tweetapp:addtweetbyform.html') yazıyoruz ve dolayısıyla html olusturmamız gerekio
'''

#bu da farklı bi yontem form için MOdelsForm gordgn gibi önce import ettik sonra:
class AddTweetModelForm(ModelForm):
    class Meta:
        model= Tweet
        fields = ["username","message"]#modelde nickname ve message column olusturuluo bize buraya ordan yazıyoruz
#views.py dede bunu kaydetmemiz gerekio ve tabiki html dosyası bunları yaptım bakabilirsin nası yaptıgıma 
#bunda gordgn gibi charfield fln bi şey girmiyoruz bunda bunu kendisi yapıyo biz sadece hangi fieldların olucagını soyledik

djangotweet/tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse,reverse_lazy
from tweetapp.forms import AddTweetForm, AddTweetModelForm
from django.contrib.auth.decorators import login_required #giriş yapmayan kullanıcının goremiycegi seyler için
from django.contrib.auth.forms import UserCreationForm #kullanıcı olstrmak için sınıf temelli yapıcaz bunu import etmemiz gerekio video 256 dan detyalara bakablrsn 
from django.views.generic import CreateView #bu class formlrını kullanabilmek için gorunum olusturmayıdda import ettikS

# Create your views here.
def listtweet(request):
    all_tweets=models.Tweet.objects.all()
    tweet_dictionary={"tweets":all_tweets}
    return render(request,'tweetapp/listtweet.html',context=tweet_dictionary)
@login_required(login_url="/login")#bunu yapınca burayı sadece giriş yapan kullanıcılar kullanabiliyo ve giriş yapmayan kullanıcılar bunu yapmaya calısıtgında login sayfasına yonlendirmesi için paranytez içindekileri yazdık
def addtweet(request):
    if request.POST:
        #nickname=(request.POST["nick name"])#bu sayede html e açtgmz formda kullanıcının girdigi nickname ve messageyi alabiliyoruz,258.videodan sonra buna ihtiyacmz kalmıo kullanıcı zaten giriş yapmış olcak cunku
        message=(request.POST["message"])
        models.Tweet.objects.create(username=request.user,message=message)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request,'tweetapp/addtweet.html')

def addtweetbyform(request):
    if request.method=="POST":
        form=AddTweetForm(request.POST)#forms un guzelliklerinden direkt requestPOST vererek yani bana gelen istegi vererek hazır bir dolu şekilde olusturabiliyorum
        if form.is_valid():#bu eger form gecerliyse demek
            nickname=form.cleaned_data["nickname_input"]
            message=form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form")
            return render(request,'tweetapp/addtweetbyform.html',context={"form":form})
    else:
        form=AddTweetForm()#htmlinde bunun oldugunu belirtebilmek için bunu yapmamız ve contexte belirtmemiz gerekir
        return render(request,'tweetapp/addtweetbyform.html',context={"form":form})

def addtweetbymodelform(request):
     if request.method=="POST":
        form=AddTweetModelForm(request.POST)#forms un guzelliklerinden direkt requestPOST vererek yani bana gelen istegi vererek hazır bir dolu şekilde olusturabiliyorum
        if form.is_valid():#bu eger form gecerliyse demek
            nickname=form.cleaned_data["nickname"]
            message=form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form")
            return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})
     else:
        form=AddTweetModelForm()#htmlinde bunun oldugunu belirtebilmek için bunu yapmamız ve contexte belirtmemiz gerekir
        return render(request, 'tweetapp/addtweetbymodelform.html',context={"form":form})
@login_required
def DeleteTweet(request,id):
    tweet=models.Tweet.objects.get(pk=id)
    #aslnda artk burda sileblrz tweeti ama ben daha guvenli olması için tekrar kontrol edicem
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect(reverse('tweetapp:listtweet'))#şimdi bunu urls.py ye tanımlıcaz

class SignUpView(CreateView):
    form_class=UserCreationForm #hangi formu kullanıcagımızı belirtiyoruz
    success_url=reverse_lazy("login")#eger firiş başarılı olursa nereye yonlendircegimzi giriyoruz#her reverse yaptgmzda bzm için hesaplanıo ama kullanıcı bunu bir kez kullanıcak o yuzden biraz gereksiz cok kullanılmaz bu yuzden revrse_lazy import edp onu kullanıız u sayede sadece buraya ulaşıldıgında hesaplanır surekli boosu bosuna hesaplanmaz bu yzuden reverse yerine reverse_lazy kullandık
    template_name="registration/signup.html"#html mizi veriyoruz

djangotweet/templates/base.html
{%load static%}<!--static i almak için formu ozelleştirmek için-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{%static 'tweetapp/customform.css'%}"><!--static i cormesi için formumu ozelleştirebilmek için yaptuım-->
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{%url 'tweetapp:listtweet'%}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet'%}">List Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'tweetapp:addtweet'%}">Add Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'login' %}">Login</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link" href="{%url 'logout' %}?next=/">Logout</a></li>--><!--linke direkt bir şey yapmadan yani authentication yapnca logout zatn bzm için olusturukldugundan direkt verebiliyoruz html de vermeye gerek yok yani istersek çıkış yaptınız yazdırablrz ama genelde bzmde yaptgmz gibi ana sayfaya yonlendirilir yonlendirmek içinde suslu parantezden sonra ?next= şeklinde neeye yonlendirceksek yazabilirizBU OLMADI NİYE BİLMİYORUM -->
              
              
              <li class="nav-item">
                <form class="nav-item" method="post" action="{% url 'logout' %}?next=/">  <!--BASTAKİ URLS.PY AUTh urlsni verdgmz için logout u direkt gorebilio ?next= e burdan sonra bu işlemi yaptktan sonra nereye yonlendircegimizi belirtme için-->
                  {% csrf_token %}
                  <button type="submit">Logout</button>
             </form>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'tweetapp:signup' %}">SignUp</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link" href="{%url 'tweetapp:addtweetbyform'%}">Add Tweet by Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'tweetapp:addtweetbymodelform'%}">Add Tweet by ModelForm</a>
              </li>
              -->
             
            </ul>
            
          </div>
        </div>
      </nav>
      
      {%block content%}
    {% endblock %}
    
</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{%extends 'base.html'%}

{%block content%}


<form action="" method="POST">
    {% csrf_token %}
      <div class="container" style="width: 50%;">
      <!--artk kullanıcı giriş yapıyo ve nicknemeye ihtiyacmz olmadıgı için burayı kullanmıyoruz 258.videodan sonra
        <div class="mb-3">
        
        <label for="nick name" class="form-label">Nick Name</label>
        <input type="text" class="form-control" id="nick name" name="nick name">
        
      </div>
      -->
      <div class="mb-3">
        <label for="message" class="form-label">Message</label>
        <input type="text" class="form-control" id="message" name="message">
      </div>
      
      <button type="submit" class="btn btn-primary">Send Tweet</button>
  </div>
  </form>
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{%extends 'base.html'%}
{%load static%}<!--csss i almak için yapıoruz settings den static in oldugunu bulablr bu yuzden ismini static koyduk ve base.html e stati in linkini vercez-->

{%block content%}


<div class="container tweetform"><!--bunuda isimini belirtmek için div açtıkcss de .tewwtform ile işlem yapabilmek için containerde bootstrapdeki container-->
<form action="" method="POST">
    {% csrf_token %}
    {%for field in form%}
    <div class="form-control">
      {{field.label_tag}}
        {{field}}
      </div>
    {%endfor%}
    <!--bunu ozellestirebilirsin gün57 249. video izle-->
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </form>
</div>
  <!--bunu ozelleştirmek için css dosyası accaz tweetapp in içine static die bir folder onun içinede tweetapp onun içinede css dosyamı acacam -->
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{%extends 'base.html'%}
{%load static%}<!--csss i almak için yapıoruz settings den static in oldugunu bulablr bu yuzden ismini static koyduk ve base.html e stati in linkini vercez-->

{%block content%}


<div class="container tweetform"><!--bunuda isimini belirtmek için div açtıkcss de .tewwtform ile işlem yapabilmek için containerde bootstrapdeki container-->
    <form action="" method="POST">
        {% csrf_token %}
        {%for field in form%}
        <div class="form-control">
            {{field.label_tag}}
            {{field}}
          </div>
        {%endfor%}
        <!--bunu ozellestirebilirsin gün57 249. video izle-->
        <button type="submit" class="btn btn-primary">Send Tweet</button>
      </form>
    </div>
 
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends 'base.html' %}

{%block content%}

    <div class="container" style="width: 50%;">
        {%for tweet in tweets%}
            <div class="card" style="padding: 10px;">
                <div class="card-header" style="background-color:cornflowerblue  ;">
                   <h4> {{tweet.username}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">{{tweet.message}}</p>
                </div>
                {%if tweet.username == user%}<!--kullanıcının kendi tweetini silebilmesi için bu == user yaptgmz için her kullanıcının kendi paylastıgı tweetde ddelete butonu gozukcek-->
                <a href="{%url 'tweetapp:DeleteTweet' id=tweet.id%}" class="btn btn-danger">Delete</a>
                <!--bunu backend dede kontrol etmemiz lazım vies.py de yeni fonksiyon yazdım git bak id de verdgmz için id yide gordgn gibi alablrsn-->
                

                {%endif%}
            </div>
        {%endfor%}
    </div>

    
        
{%endblock%}